apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "30"
  namespace: example06
  generateName: enable-alerts-
  labels:
    codefresh.io/cert: enable-job  
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "3"
      restartPolicy: Never
  backoffLimit: 2    
